const { SlashCommandBuilder } = require('discord.js');

module.exports = [
    { data: new SlashCommandBuilder().setName('meme').setDescription('Manda un meme random'),
    execute: async i => await i.reply('😂 Meme random')},
    { data: new SlashCommandBuilder().setName('chiste').setDescription('Cuenta un chiste malo'),
    execute: async i => await i.reply('¿Qué le dice un techo a otro? ¡Techo de menos!')},
    { data: new SlashCommandBuilder().setName('8ball').setDescription('Pregunta a la bola 8 mágica').addStringOption(o=>o.setName('pregunta').setDescription('Tu pregunta').setRequired(true)),
    execute: async i => {
        const r = ['Si','No','Tal vez','Definitivamente'];
        await i.reply(`🎱 Pregunta: ${i.options.getString('pregunta')}\nRespuesta: ${r[Math.floor(Math.random()*4)]}`);
    }},
    { data: new SlashCommandBuilder().setName('ship').setDescription('Calcula compatibilidad entre 2 personas').addUserOption(o=>o.setName('p1').setDescription('Persona 1').setRequired(true)).addUserOption(o=>o.setName('p2').setDescription('Persona 2').setRequired(true)),
    execute: async i => await i.reply(`💖 ${i.options.getUser('p1').username} x ${i.options.getUser('p2').username} = ${Math.floor(Math.random()*100)}%`)},
    { data: new SlashCommandBuilder().setName('dado').setDescription('Tira un dado de 6 caras'),
    execute: async i => await i.reply(`🎲 Sacaste: ${Math.floor(Math.random()*6)+1}`)},
    { data: new SlashCommandBuilder().setName('coinflip').setDescription('Lanza una moneda cara o cruz'),
    execute: async i => await i.reply(`🪙 Salió: ${Math.random()<0.5?'Cara':'Cruz'}`)},
    { data: new SlashCommandBuilder().setName('pp').setDescription('Mide el tamaño del pp').addUserOption(o=>o.setName('usuario').setDescription('Usuario a medir')),
    execute: async i => await i.reply(`🍆 ${i.options.getUser('usuario')||i.user} tiene: ${'='.repeat(Math.floor(Math.random()*20))}D`)},
    { data: new SlashCommandBuilder().setName('gay').setDescription('Medidor de gay').addUserOption(o=>o.setName('usuario').setDescription('Usuario')),
    execute: async i => await i.reply(`🏳️‍🌈 ${i.options.getUser('usuario')||i.user} es ${Math.floor(Math.random()*100)}% gay`)},
    { data: new SlashCommandBuilder().setName('slap').setDescription('Cachetear a alguien').addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true)),
    execute: async i => await i.reply(`👋 ${i.user} cachetea a ${i.options.getUser('usuario')}`)},
    { data: new SlashCommandBuilder().setName('hug').setDescription('Abrazar a alguien').addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true)),
    execute: async i => await i.reply(`🤗 ${i.user} abraza a ${i.options.getUser('usuario')}`)},
    { data: new SlashCommandBuilder().setName('kiss').setDescription('Besar a alguien').addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true)),
    execute: async i => await i.reply(`😘 ${i.user} besa a ${i.options.getUser('usuario')}`)},
    { data: new SlashCommandBuilder().setName('roast').setDescription('Insultar de forma chistosa').addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true)),
    execute: async i => await i.reply(`🔥 ${i.options.getUser('usuario')} eres tan lento que sales en cámara lenta`)},
    { data: new SlashCommandBuilder().setName('compliment').setDescription('Dar un cumplido').addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true)),
    execute: async i => await i.reply(`✨ ${i.options.getUser('usuario')} eres increíble!`)},
    { data: new SlashCommandBuilder().setName('rate').setDescription('Calificar algo del 1 al 10').addStringOption(o=>o.setName('cosa').setDescription('Que quieres calificar').setRequired(true)),
    execute: async i => await i.reply(`⭐ Califico ${i.options.getString('cosa')} con ${Math.floor(Math.random()*10)+1}/10`)},
    { data: new SlashCommandBuilder().setName('fact').setDescription('Da un dato curioso random'),
    execute: async i => await i.reply('🧠 Los pulpos tienen 3 corazones')},
    { data: new SlashCommandBuilder().setName('advice').setDescription('Da un consejo random'),
    execute: async i => await i.reply('💡 Consejo: Toma agua')},
    { data: new SlashCommandBuilder().setName('joke').setDescription('Cuenta un chiste en ingles'),
    execute: async i => await i.reply('Why did the chicken cross the road? To get to the other side!')},
    { data: new SlashCommandBuilder().setName('quote').setDescription('Muestra una frase motivacional'),
    execute: async i => await i.reply('📜 "El que persevera, alcanza"')},
    { data: new SlashCommandBuilder().setName('pickup').setDescription('Dice un piropo'),
    execute: async i => await i.reply('😏 ¿Crees en amor a primera vista o paso otra vez?')},
    { data: new SlashCommandBuilder().setName('random').setDescription('Genera un numero aleatorio'),
    execute: async i => await i.reply(`🎲 Numero: ${Math.floor(Math.random()*1000)}`)}
];
