const { SlashCommandBuilder } = require('discord.js');

module.exports = [
    { data: new SlashCommandBuilder().setName('balance').setDescription('Ver dinero').addUserOption(o=>o.setName('usuario')),
    execute: async i => await i.reply(`💰 ${i.options.getUser('usuario')||i.user} tiene: $1000`)},
    { data: new SlashCommandBuilder().setName('daily').setDescription('Reclamar diario'),
    execute: async i => await i.reply('🎁 Reclamaste $500 diarios!')},
    { data: new SlashCommandBuilder().setName('work').setDescription('Trabajar'),
    execute: async i => await i.reply(`💼 Trabajaste y ganaste $${Math.floor(Math.random()*200)+100}`)},
    { data: new SlashCommandBuilder().setName('rob').setDescription('Robar').addUserOption(o=>o.setName('usuario').setRequired(true)),
    execute: async i => await i.reply(`🦹 Robaste $${Math.floor(Math.random()*500)} a ${i.options.getUser('usuario')}`)},
    { data: new SlashCommandBuilder().setName('pay').setDescription('Pagar').addUserOption(o=>o.setName('usuario').setRequired(true)).addIntegerOption(o=>o.setName('cantidad').setRequired(true)),
    execute: async i => await i.reply(`💸 Le pagaste $${i.options.getInteger('cantidad')} a ${i.options.getUser('usuario')}`)},
    { data: new SlashCommandBuilder().setName('shop').setDescription('Tienda'),
    execute: async i => await i.reply('🛒 Tienda: Coche $5000, Casa $20000')},
    { data: new SlashCommandBuilder().setName('buy').setDescription('Comprar').addStringOption(o=>o.setName('item').setRequired(true)),
    execute: async i => await i.reply(`✅ Compraste: ${i.options.getString('item')}`)},
    { data: new SlashCommandBuilder().setName('sell').setDescription('Vender').addStringOption(o=>o.setName('item').setRequired(true)),
    execute: async i => await i.reply(`💵 Vendiste: ${i.options.getString('item')}`)},
    { data: new SlashCommandBuilder().setName('inventory').setDescription('Inventario'),
    execute: async i => await i.reply('🎒 Inventario: Vacío')},
    { data: new SlashCommandBuilder().setName('leaderboard').setDescription('Top ricos'),
    execute: async i => await i.reply('🏆 Top 1: $100000')},
    { data: new SlashCommandBuilder().setName('crime').setDescription('Cometer crimen'),
    execute: async i => await i.reply(`👮 ${Math.random()<0.5?'Te atraparon! Multa $300':'Ganaste $400!'}`)},
    { data: new SlashCommandBuilder().setName('gamble').setDescription('Apostar').addIntegerOption(o=>o.setName('cantidad').setRequired(true)),
    execute: async i => await i.reply(`🎰 ${Math.random()<0.5?'Perdiste':'Ganaste'} $${i.options.getInteger('cantidad')}`)},
    { data: new SlashCommandBuilder().setName('beg').setDescription('Mendigar'),
    execute: async i => await i.reply(`🙏 Te dieron $${Math.floor(Math.random()*50)}`)},
    { data: new SlashCommandBuilder().setName('deposit').setDescription('Depositar').addIntegerOption(o=>o.setName('cantidad').setRequired(true)),
    execute: async i => await i.reply(`🏦 Depositaste $${i.options.getInteger('cantidad')}`)},
    { data: new SlashCommandBuilder().setName('withdraw').setDescription('Retirar').addIntegerOption(o=>o.setName('cantidad').setRequired(true)),
    execute: async i => await i.reply(`💳 Retiraste $${i.options.getInteger('cantidad')}`)},
    { data: new SlashCommandBuilder().setName('slots').setDescription('Tragamonedas'),
    execute: async i => await i.reply('🎰 🍒 🍒 🍒 Ganaste!')},
    { data: new SlashCommandBuilder().setName('fish').setDescription('Pescar'),
    execute: async i => await i.reply(`🎣 Pescaste un ${['pez','tiburon','bota'][Math.floor(Math.random()*3)]}`)},
    { data: new SlashCommandBuilder().setName('hunt').setDescription('Cazar'),
    execute: async i => await i.reply(`🏹 Cazaste un ${['conejo','ciervo','oso'][Math.floor(Math.random()*3)]}`)},
    { data: new SlashCommandBuilder().setName('mine').setDescription('Minar'),
    execute: async i => await i.reply(`⛏️ Minaste ${['carbon','hierro','diamante'][Math.floor(Math.random()*3)]}`)},
    { data: new SlashCommandBuilder().setName('lottery').setDescription('Lotería'),
    execute: async i => await i.reply('🎟️ Compraste boleto de lotería')}
];
